unique_ids:
  forms:
    Form1: YK7IQJLWG4EQMPNU7ILT2ASOX4RVHQRT
  modules: {}
  server_modules: {}
  assets:
    theme.css: 35SZS5N2WPY5HV5JCAMHBZDWBREHQBI5
    standard-page.html: 7FCGRNUSTAPLISWHDVSANEMLYRCW6J5T
  scripts: {}
