unique_ids:
  forms:
    Form1.ItemTemplate1: '1724715827610449809258811.2943'
    Form1: YK7IQJLWG4EQMPNU7ILT2ASOX4RVHQRT
  modules: {}
  server_modules:
    ServerModule1: '1724713197960454308083460.35925'
  assets:
    standard-page.html: 7FCGRNUSTAPLISWHDVSANEMLYRCW6J5T
    theme.css: 35SZS5N2WPY5HV5JCAMHBZDWBREHQBI5
  scripts: {}
